### ISSUE TITLE
createSongNew doesn't include _H to header names.

### ISSUE THREAD

**Issue by jaygarcia** [ModusCreateOrg/trackerEditor#14]
I loaded `evade4ch.atm` into the version in master.

It exports:
```
#ifndef EVADE4CH
#define EVADE4CH
... Music stuff
```

It should be:
```
#ifndef EVADE4CH_H
#define EVADE4CH_H
... Music stuff
```

**Comment by slemmon** [comment]
Just added this fix to my current PR that I'll send up later tonight or tomorrow morning.  Fix is forthcoming!!

**Comment by slemmon** [comment]
Fixed with: https://github.com/ModusCreateOrg/trackerEditor/pull/15
