### ISSUE TITLE
showCode has problems with B-4 notes

### ISSUE THREAD

**Issue by jaygarcia** [ModusCreateOrg/trackerEditor#20]
Steps to reproduce:
- New tune track
- Draw 1 or more `B` notes with an octave of `4`.
- Open JS console
- Press "Show Code"
- Notice Exception.

The `mod 12` logic is broken as `24 % 12 == 0` and there is no note with a value of `0`. 

It's most likely that any `B`  note at any octave  (multiple of twelve)  results in similar problems.

**Comment by slemmon** [comment]
Fixed by: https://github.com/ModusCreateOrg/trackerEditor/pull/21
