### ISSUE TITLE
Need to figure out a way to have more than one song living in a game

### ISSUE THREAD

**Issue by jaygarcia** [ModusCreateOrg/trackerEditor#8]
I think that the current path we're on provides the opportunity for name collisions.

We need a way to write in things like "song name" and somehow make it compatible w/ the c-generated data.

So for example, a song by the name of "Evade Stage 1" would need to be converted to "Evade_Stage_1" and have all of the name prefix things like `pattern_0` so that we don't have collisions. 

the name "score" should also be replaced with "Evade_Stage_1_score" or something like that.

**Comment by jaygarcia** [comment]
The song name field should be an input field a the top of the page.

**Comment by slemmon** [comment]
The song name from the song field should live in the tracker file when saved as well.

**Comment by slemmon** [comment]
PR to address the issue: https://github.com/ModusCreateOrg/trackerEditor/pull/12

**Comment by slemmon** [comment]
Closing with merge of https://github.com/ModusCreateOrg/trackerEditor/pull/12
